export const SET_USER = "SET_USER";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const REMOVE_USER_TOKEN = "REMOVE_USER_TOKEN";
export const REMOVE_USER = "REMOVE_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const GET_USER_PERIOD_NAME = "GET_USER_PERIOD_NAME";

export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";

export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";
